### ISSUE TITLE
Widget is using deprecated getApiRequest id

### ISSUE THREAD

**Issue by juhamust** [plouc/mozaik-ext-weather#2]
Recent change in Mozaik deprecates the usage of unique ids, like https://github.com/plouc/mozaik-ext-weather/blob/master/src/components/Weather.jsx#L67

```
Error: Invalid request id "weather.combined.Helsinki.FI.en.2", should be something like 'api_id.method'
    at Bus.clientSubscription (/app/node_modules/mozaik/lib/Bus.js:92:27)
```

Earlier, however, the same data was returned if the id did not change while params did.

**Comment by juhamust** [comment]
Confirmed. It seems the extension/client API is only called once - even if the params do change.

**Comment by plouc** [comment]
Fixed in https://github.com/plouc/mozaik/commit/f4bffb10e9b9b4fe85a6fc8e1e50c05aa5e1397c, the old format is the with `api_id.method.unique_param` is the good one
